' vbsexpr.vbs <output>: what built-in functions and operators answer for Null, Empty, objects and bad values
Option Explicit
Dim fso, out, r, d, x_undefined_var
Set fso = CreateObject("Scripting.FileSystemObject")
Set out = fso.CreateTextFile(WScript.Arguments(0), True, True)
Set d = CreateObject("Scripting.Dictionary")
Sub show(what)
    If Err.Number = 0 Then
        out.WriteLine what & vbTab & "ok" & vbTab & TypeName(r)
    Else
        out.WriteLine what & vbTab & Err.Number
    End If
    Err.Clear
End Sub
On Error Resume Next
r = Empty : r = CBool(Null) : show "CBool(Null)"
r = Empty : r = CByte(Null) : show "CByte(Null)"
r = Empty : r = CCur(Null) : show "CCur(Null)"
r = Empty : r = CDate(Null) : show "CDate(Null)"
r = Empty : r = CDbl(Null) : show "CDbl(Null)"
r = Empty : r = CInt(Null) : show "CInt(Null)"
r = Empty : r = CLng(Null) : show "CLng(Null)"
r = Empty : r = CSng(Null) : show "CSng(Null)"
r = Empty : r = CStr(Null) : show "CStr(Null)"
r = Empty : r = CBool(Empty) : show "CBool(Empty)"
r = Empty : r = CInt(Empty) : show "CInt(Empty)"
r = Empty : r = CStr(Empty) : show "CStr(Empty)"
r = Empty : r = CInt("x") : show "CInt(""x"")"
r = Empty : r = CLng("1e3") : show "CLng(""1e3"")"
r = Empty : r = CByte(256) : show "CByte(256)"
r = Empty : r = CByte(-1) : show "CByte(-1)"
r = Empty : r = CInt(32768) : show "CInt(32768)"
r = Empty : r = CLng(2147483648) : show "CLng(2147483648)"
r = Empty : r = CBool("yes") : show "CBool(""yes"")"
r = Empty : r = CBool("true") : show "CBool(""true"")"
r = Empty : r = Asc(Null) : show "Asc(Null)"
r = Empty : r = Asc("") : show "Asc("""")"
r = Empty : r = Chr(Null) : show "Chr(Null)"
r = Empty : r = Chr(256) : show "Chr(256)"
r = Empty : r = ChrW(65536) : show "ChrW(65536)"
r = Empty : r = Hex(Null) : show "Hex(Null)"
r = Empty : r = Oct(Null) : show "Oct(Null)"
r = Empty : r = Fix(Null) : show "Fix(Null)"
r = Empty : r = Int(Null) : show "Int(Null)"
r = Empty : r = Abs(Null) : show "Abs(Null)"
r = Empty : r = Sgn(Null) : show "Sgn(Null)"
r = Empty : r = Sqr(Null) : show "Sqr(Null)"
r = Empty : r = Sqr(-1) : show "Sqr(-1)"
r = Empty : r = Log(0) : show "Log(0)"
r = Empty : r = Exp(1000) : show "Exp(1000)"
r = Empty : r = Len(Null) : show "Len(Null)"
r = Empty : r = LCase(Null) : show "LCase(Null)"
r = Empty : r = Trim(Null) : show "Trim(Null)"
r = Empty : r = Left(Null, 1) : show "Left(Null, 1)"
r = Empty : r = Mid(Null, 1) : show "Mid(Null, 1)"
r = Empty : r = Space(Null) : show "Space(Null)"
r = Empty : r = String(Null, "a") : show "String(Null, ""a"")"
r = Empty : r = String(2, Null) : show "String(2, Null)"
r = Empty : r = StrReverse(Null) : show "StrReverse(Null)"
r = Empty : r = UBound(Null) : show "UBound(Null)"
r = Empty : r = UBound(1) : show "UBound(1)"
r = Empty : r = LBound(Empty) : show "LBound(Empty)"
r = Empty : r = Split(Null) : show "Split(Null)"
r = Empty : r = Join(Null) : show "Join(Null)"
r = Empty : r = IsArray(Null) : show "IsArray(Null)"
r = Empty : r = TypeName(Null) : show "TypeName(Null)"
r = Empty : r = Null + 1 : show "Null + 1"
r = Empty : r = Null & "a" : show "Null & ""a"""
r = Empty : r = Empty + 1 : show "Empty + 1"
r = Empty : r = 1 / Empty : show "1 / Empty"
r = Empty : r = Null = Null : show "Null = Null"
r = Empty : r = Not Null : show "Not Null"
r = Empty : r = -Null : show "-Null"
r = Empty : r = Null Mod 2 : show "Null Mod 2"
r = Empty : r = "a" + 1 : show """a"" + 1"
r = Empty : r = "1" + 1 : show """1"" + 1"
r = Empty : r = d + 1 : show "d + 1"
r = Empty : r = d & "a" : show "d & ""a"""
r = Empty : r = CStr(d) : show "CStr(d)"
r = Empty : r = d(1) : show "d(1)"
r = Empty : r = d.Count(1) : show "d.Count(1)"
r = Empty : r = Year(Null) : show "Year(Null)"
r = Empty : r = Month("x") : show "Month(""x"")"
r = Empty : r = DateAdd("x", 1, Now) : show "DateAdd(""x"", 1, Now)"
r = Empty : r = DateSerial(2026, 13, 1) : show "DateSerial(2026, 13, 1)"
r = Empty : r = TimeSerial(25, 0, 0) : show "TimeSerial(25, 0, 0)"
r = Empty : r = CDate("2026-02-30") : show "CDate(""2026-02-30"")"
r = Empty : r = FormatNumber(Null) : show "FormatNumber(Null)"
r = Empty : r = FormatNumber("x") : show "FormatNumber(""x"")"
r = Empty : r = Round(Null) : show "Round(Null)"
r = Empty : r = Round(1.5, -1) : show "Round(1.5, -1)"
r = Empty : r = InStr(1, Null, "a") : show "InStr(1, Null, ""a"")"
r = Empty : r = InStr(0, "a", "a") : show "InStr(0, ""a"", ""a"")"
r = Empty : r = Replace("a", "", "b") : show "Replace(""a"", """", ""b"")"
r = Empty : r = Filter(Null, "a") : show "Filter(Null, ""a"")"
r = Empty : r = Array(1)(1) : show "Array(1)(1)"
r = Empty : r = RGB(256, 0, 0) : show "RGB(256, 0, 0)"
r = Empty : r = RGB(-1, 0, 0) : show "RGB(-1, 0, 0)"
r = Empty : r = Rnd(Null) : show "Rnd(Null)"
r = Empty : r = CreateObject("") : show "CreateObject("""")"
r = Empty : r = GetObject("") : show "GetObject("""")"
r = Empty : r = ScriptEngine() : show "ScriptEngine()"
r = Empty : r = LoadPicture("x") : show "LoadPicture(""x"")"
r = Empty : r = Escape(Null) : show "Escape(Null)"
r = Empty : r = Unescape(Null) : show "Unescape(Null)"
r = Empty : r = IsNumeric(Null) : show "IsNumeric(Null)"
r = Empty : r = Nothing Is Nothing : show "Nothing Is Nothing"
r = Empty : r = d Is Nothing : show "d Is Nothing"
r = Empty : r = 1 Is Nothing : show "1 Is Nothing"
r = Empty : r = x_undefined_var + 1 : show "x_undefined_var + 1"
r = Empty : r = Array(1, 2)(0, 0) : show "Array(1, 2)(0, 0)"
r = Empty : r = UBound(Array(), 2) : show "UBound(Array(), 2)"
r = Empty : r = Mid("abc", 2, -1) : show "Mid(""abc"", 2, -1)"
r = Empty : r = Left("abc", -1) : show "Left(""abc"", -1)"
r = Empty : r = Right("abc", Null) : show "Right(""abc"", Null)"
r = Empty : r = InStrRev("abc", "b", 0) : show "InStrRev(""abc"", ""b"", 0)"
r = Empty : r = Split("a,b", ",", 0)(0) : show "Split(""a,b"", "","", 0)(0)"
r = Empty : r = CLng(" 12 ") : show "CLng("" 12 "")"
r = Empty : r = CDbl("1,5") : show "CDbl(""1,5"")"
r = Empty : r = CDbl("1.5") : show "CDbl(""1.5"")"
r = Empty : r = Int("2.7") : show "Int(""2.7"")"
r = Empty : r = Fix(-2.7) : show "Fix(-2.7)"
r = Empty : r = DateValue(Null) : show "DateValue(Null)"
r = Empty : r = TimeValue("25:00") : show "TimeValue(""25:00"")"
r = Empty : r = WeekdayName(8) : show "WeekdayName(8)"
r = Empty : r = MonthName(0) : show "MonthName(0)"
r = Empty : r = FormatDateTime(Now, 5) : show "FormatDateTime(Now, 5)"
r = Empty : r = FormatPercent(Null) : show "FormatPercent(Null)"
r = Empty : r = FormatCurrency("x") : show "FormatCurrency(""x"")"
r = Empty : r = Hex(-1) : show "Hex(-1)"
r = Empty : r = Oct(2147483648) : show "Oct(2147483648)"
out.Close
