/*** Autogenerated by WIDL 11.19 from tools/prefixupdateprobe/rpcsd.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __rpcsd_h__
#define __rpcsd_h__

/* Forward declarations */

/* Headers for imported files */


#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * prefixupdate_rpcsd interface (v1.0)
 */
#ifndef __prefixupdate_rpcsd_INTERFACE_DEFINED__
#define __prefixupdate_rpcsd_INTERFACE_DEFINED__

extern RPC_IF_HANDLE c_prefixupdate_rpcsd_v1_0_c_ifspec;
extern RPC_IF_HANDLE s_prefixupdate_rpcsd_v1_0_s_ifspec;
/* client prototype */
LONG __cdecl c_ping(
    handle_t binding,
    LONG value);

/* server prototype */
LONG __cdecl s_ping(
    handle_t binding,
    LONG value);


#endif  /* __prefixupdate_rpcsd_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __rpcsd_h__ */
