/*** Autogenerated by WIDL 11.19 from tools/prefixupdateprobe/rpcsd.idl - Do not edit ***/
#include <string.h>

#include "rpcsd.h"

#define TYPE_FORMAT_STRING_SIZE 3
#define PROC_FORMAT_STRING_SIZE 43

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

/*****************************************************************************
 * prefixupdate_rpcsd interface
 */

static const RPC_CLIENT_INTERFACE prefixupdate_rpcsd___RpcClientInterface =
{
    sizeof(RPC_CLIENT_INTERFACE),
    {{0x84f7de62,0x905a,0x4a5b,{0x81,0xea,0x58,0x69,0xb0,0xd7,0x8a,0xa0}},{1,0}},
    {{0x8a885d04,0x1ceb,0x11c9,{0x9f,0xe8,0x08,0x00,0x2b,0x10,0x48,0x60}},{2,0}},
    0,
    0,
    0,
    0,
    0,
    0,
};
RPC_IF_HANDLE c_prefixupdate_rpcsd_v1_0_c_ifspec = (RPC_IF_HANDLE)& prefixupdate_rpcsd___RpcClientInterface;

static const MIDL_STUB_DESC prefixupdate_rpcsd_StubDesc;

static RPC_BINDING_HANDLE prefixupdate_rpcsd__MIDL_AutoBindHandle;

LONG __cdecl c_ping(
    handle_t binding,
    LONG value)
{
    CLIENT_CALL_RETURN _RetVal;

    _RetVal = NdrClientCall2( &prefixupdate_rpcsd_StubDesc,
                              &__MIDL_ProcFormatString.Format[0],
                              binding,
                              value );
    return (LONG)_RetVal.Simple;
}

#if !defined(__RPC_WIN64__)
#error  Invalid build platform for this stub.
#endif

static const MIDL_STUB_DESC prefixupdate_rpcsd_StubDesc =
{
    (void *)& prefixupdate_rpcsd___RpcClientInterface,
    MIDL_user_allocate,
    MIDL_user_free,
    {
        &prefixupdate_rpcsd__MIDL_AutoBindHandle,
    },
    0,
    0,
    0,
    0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};


static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure prefixupdate_rpcsd::ping) */
        0x00,	/* explicit handle */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x0),	/* method 0 */
        NdrFcShort(0x18),	/* stack size = 24 */
        0x32,	/* FC_BIND_PRIMITIVE */
        0x00,
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 30 (parameter value) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 36 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
        0x0
    }
};

