/* The Office scheduled tasks as Windows (build 29671) exports them, from Export-ScheduledTask. */

static const struct
{
    const char *name;
    const WCHAR *xml;
}
office_tasks[] =
{
    {"Office_Actions_Server",
        L"<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n"
        L"<Task version=\"1.2\" xmlns=\"http://schemas.microsoft.com/windows/2004/02/mit/task\">\n"
        L"  <RegistrationInfo>\n"
        L"    <Description>This task updates the availability states of Windows Actions.</Description>\n"
        L"    <URI>\\Microsoft\\Office\\Office Actions Server</URI>\n"
        L"  </RegistrationInfo>\n"
        L"  <Principals>\n"
        L"    <Principal id=\"Author\">\n"
        L"      <GroupId>S-1-5-32-545</GroupId>\n"
        L"    </Principal>\n"
        L"  </Principals>\n"
        L"  <Settings>\n"
        L"    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n"
        L"    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n"
        L"    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\n"
        L"    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n"
        L"    <StartWhenAvailable>true</StartWhenAvailable>\n"
        L"    <IdleSettings>\n"
        L"      <StopOnIdleEnd>false</StopOnIdleEnd>\n"
        L"      <RestartOnIdle>false</RestartOnIdle>\n"
        L"    </IdleSettings>\n"
        L"  </Settings>\n"
        L"  <Triggers>\n"
        L"    <LogonTrigger>\n"
        L"      <ExecutionTimeLimit>PT3M</ExecutionTimeLimit>\n"
        L"      <Delay>PT10M</Delay>\n"
        L"    </LogonTrigger>\n"
        L"    <TimeTrigger>\n"
        L"      <StartBoundary>2025-01-01T00:00:00</StartBoundary>\n"
        L"      <Enabled>false</Enabled>\n"
        L"      <Repetition>\n"
        L"        <Interval>PT1H</Interval>\n"
        L"      </Repetition>\n"
        L"    </TimeTrigger>\n"
        L"  </Triggers>\n"
        L"  <Actions Context=\"Author\">\n"
        L"    <Exec>\n"
        L"      <Command>C:\\Program Files\\Microsoft Office\\root\\VFS\\ProgramFilesCommonX64\\Microsoft Shared\\Office16\\ActionsServer\\ActionsServer.exe</Command>\n"
        L"      <Arguments>availabilitycheck</Arguments>\n"
        L"    </Exec>\n"
        L"  </Actions>\n"
        L"</Task>"
    },
    {"Office_Automatic_Updates_2.0",
        L"<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n"
        L"<Task version=\"1.2\" xmlns=\"http://schemas.microsoft.com/windows/2004/02/mit/task\">\n"
        L"  <RegistrationInfo>\n"
        L"    <Date>2017-08-05T12:13:18.0043321</Date>\n"
        L"    <Author>Microsoft Office</Author>\n"
        L"    <Description>This task ensures that your Microsoft Office installation can check for updates.</Description>\n"
        L"    <URI>\\Microsoft\\Office\\Office Automatic Updates 2.0</URI>\n"
        L"  </RegistrationInfo>\n"
        L"  <Principals>\n"
        L"    <Principal id=\"Author\">\n"
        L"      <UserId>S-1-5-18</UserId>\n"
        L"      <RunLevel>HighestAvailable</RunLevel>\n"
        L"    </Principal>\n"
        L"  </Principals>\n"
        L"  <Settings>\n"
        L"    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n"
        L"    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n"
        L"    <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n"
        L"    <RestartOnFailure>\n"
        L"      <Count>3</Count>\n"
        L"      <Interval>PT30M</Interval>\n"
        L"    </RestartOnFailure>\n"
        L"    <StartWhenAvailable>true</StartWhenAvailable>\n"
        L"    <IdleSettings>\n"
        L"      <StopOnIdleEnd>false</StopOnIdleEnd>\n"
        L"      <RestartOnIdle>false</RestartOnIdle>\n"
        L"    </IdleSettings>\n"
        L"  </Settings>\n"
        L"  <Triggers>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2010-12-16T03:00:00</StartBoundary>\n"
        L"      <RandomDelay>PT12H</RandomDelay>\n"
        L"      <ScheduleByWeek>\n"
        L"        <WeeksInterval>1</WeeksInterval>\n"
        L"        <DaysOfWeek>\n"
        L"          <Sunday />\n"
        L"          <Monday />\n"
        L"          <Tuesday />\n"
        L"          <Wednesday />\n"
        L"          <Thursday />\n"
        L"          <Friday />\n"
        L"          <Saturday />\n"
        L"        </DaysOfWeek>\n"
        L"      </ScheduleByWeek>\n"
        L"    </CalendarTrigger>\n"
        L"    <LogonTrigger>\n"
        L"      <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"      <Delay>PT5M</Delay>\n"
        L"    </LogonTrigger>\n"
        L"    <IdleTrigger>\n"
        L"      <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"    </IdleTrigger>\n"
        L"  </Triggers>\n"
        L"  <Actions Context=\"Author\">\n"
        L"    <Exec>\n"
        L"      <Command>C:\\Program Files\\Common Files\\Microsoft Shared\\ClickToRun\\OfficeC2RClient.exe</Command>\n"
        L"      <Arguments>/frequentupdate SCHEDULEDTASK displaylevel=False</Arguments>\n"
        L"    </Exec>\n"
        L"  </Actions>\n"
        L"</Task>"
    },
    {"Office_Background_Push_Maintenance",
        L"<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n"
        L"<Task version=\"1.3\" xmlns=\"http://schemas.microsoft.com/windows/2004/02/mit/task\">\n"
        L"  <RegistrationInfo>\n"
        L"    <Version>16.0.0</Version>\n"
        L"    <Date>2024-10-01T00:00:00</Date>\n"
        L"    <Author>Microsoft Office</Author>\n"
        L"    <Description>Task is used to periodically update device configuration with Microsoft to ensure the latest apps and features are available on this device</Description>\n"
        L"    <URI>\\Microsoft\\Office\\Office Background Push Maintenance</URI>\n"
        L"  </RegistrationInfo>\n"
        L"  <Principals>\n"
        L"    <Principal id=\"Author\">\n"
        L"      <GroupId>S-1-5-4</GroupId>\n"
        L"    </Principal>\n"
        L"  </Principals>\n"
        L"  <Settings>\n"
        L"    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n"
        L"    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>\n"
        L"    <ExecutionTimeLimit>PT4H</ExecutionTimeLimit>\n"
        L"    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n"
        L"    <RestartOnFailure>\n"
        L"      <Count>3</Count>\n"
        L"      <Interval>PT1M</Interval>\n"
        L"    </RestartOnFailure>\n"
        L"    <StartWhenAvailable>true</StartWhenAvailable>\n"
        L"    <RunOnlyIfNetworkAvailable>true</RunOnlyIfNetworkAvailable>\n"
        L"    <IdleSettings>\n"
        L"      <StopOnIdleEnd>true</StopOnIdleEnd>\n"
        L"      <RestartOnIdle>false</RestartOnIdle>\n"
        L"    </IdleSettings>\n"
        L"    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\n"
        L"  </Settings>\n"
        L"  <Triggers>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2010-01-01T04:03:23</StartBoundary>\n"
        L"      <ExecutionTimeLimit>PT4H</ExecutionTimeLimit>\n"
        L"      <Repetition>\n"
        L"        <Interval>PT12H</Interval>\n"
        L"        <Duration>P1D</Duration>\n"
        L"      </Repetition>\n"
        L"      <ScheduleByDay>\n"
        L"        <DaysInterval>1</DaysInterval>\n"
        L"      </ScheduleByDay>\n"
        L"    </CalendarTrigger>\n"
        L"    <LogonTrigger>\n"
        L"      <StartBoundary>2010-01-01T00:00:00</StartBoundary>\n"
        L"    </LogonTrigger>\n"
        L"  </Triggers>\n"
        L"  <Actions Context=\"Author\">\n"
        L"    <Exec>\n"
        L"      <Command>C:\\Program Files\\Microsoft Office\\root\\vfs\\ProgramFilesCommonx64\\Microsoft Shared\\Office16\\opushutil.exe</Command>\n"
        L"      <Arguments>/pushregistration</Arguments>\n"
        L"    </Exec>\n"
        L"  </Actions>\n"
        L"</Task>"
    },
    {"Office_ClickToRun_Service_Monitor",
        L"<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n"
        L"<Task version=\"1.2\" xmlns=\"http://schemas.microsoft.com/windows/2004/02/mit/task\">\n"
        L"  <RegistrationInfo>\n"
        L"    <Date>2005-10-11T13:21:17-08:00</Date>\n"
        L"    <Author>Microsoft Office</Author>\n"
        L"    <Description>This task monitors the state of your Microsoft Office ClickToRunSvc and sends crash and error logs to Microsoft.</Description>\n"
        L"    <URI>\\Microsoft\\Office\\Office ClickToRun Service Monitor</URI>\n"
        L"  </RegistrationInfo>\n"
        L"  <Principals>\n"
        L"    <Principal id=\"Author\">\n"
        L"      <UserId>S-1-5-18</UserId>\n"
        L"      <RunLevel>HighestAvailable</RunLevel>\n"
        L"    </Principal>\n"
        L"  </Principals>\n"
        L"  <Settings>\n"
        L"    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n"
        L"    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n"
        L"    <ExecutionTimeLimit>PT30M</ExecutionTimeLimit>\n"
        L"    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n"
        L"    <StartWhenAvailable>true</StartWhenAvailable>\n"
        L"    <IdleSettings>\n"
        L"      <StopOnIdleEnd>false</StopOnIdleEnd>\n"
        L"      <RestartOnIdle>false</RestartOnIdle>\n"
        L"    </IdleSettings>\n"
        L"  </Settings>\n"
        L"  <Triggers>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2010-12-16T04:00:00</StartBoundary>\n"
        L"      <Repetition>\n"
        L"        <Interval>P1D</Interval>\n"
        L"        <Duration>P1D</Duration>\n"
        L"        <StopAtDurationEnd>true</StopAtDurationEnd>\n"
        L"      </Repetition>\n"
        L"      <RandomDelay>PT6H</RandomDelay>\n"
        L"      <ScheduleByDay>\n"
        L"        <DaysInterval>1</DaysInterval>\n"
        L"      </ScheduleByDay>\n"
        L"    </CalendarTrigger>\n"
        L"  </Triggers>\n"
        L"  <Actions Context=\"Author\">\n"
        L"    <Exec>\n"
        L"      <Command>C:\\Program Files\\Common Files\\Microsoft Shared\\ClickToRun\\OfficeC2RClient.exe</Command>\n"
        L"      <Arguments>/WatchService</Arguments>\n"
        L"    </Exec>\n"
        L"  </Actions>\n"
        L"</Task>"
    },
    {"Office_Feature_Updates",
        L"<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n"
        L"<Task version=\"1.3\" xmlns=\"http://schemas.microsoft.com/windows/2004/02/mit/task\">\n"
        L"  <RegistrationInfo>\n"
        L"    <Version>16.0.0</Version>\n"
        L"    <Date>2017-01-01T00:00:00</Date>\n"
        L"    <Author>Microsoft Office</Author>\n"
        L"    <Description>This task ensures that your Microsoft Office installation can check for feature updates.</Description>\n"
        L"    <URI>\\Microsoft\\Office\\Office Feature Updates</URI>\n"
        L"  </RegistrationInfo>\n"
        L"  <Principals>\n"
        L"    <Principal id=\"Author\">\n"
        L"      <GroupId>S-1-5-32-545</GroupId>\n"
        L"    </Principal>\n"
        L"  </Principals>\n"
        L"  <Settings>\n"
        L"    <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>\n"
        L"    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>\n"
        L"    <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n"
        L"    <RunOnlyIfNetworkAvailable>true</RunOnlyIfNetworkAvailable>\n"
        L"    <IdleSettings>\n"
        L"      <StopOnIdleEnd>false</StopOnIdleEnd>\n"
        L"      <RestartOnIdle>false</RestartOnIdle>\n"
        L"    </IdleSettings>\n"
        L"    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\n"
        L"  </Settings>\n"
        L"  <Triggers>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2017-01-01T02:10:00</StartBoundary>\n"
        L"      <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"      <RandomDelay>PT4H</RandomDelay>\n"
        L"      <ScheduleByDay>\n"
        L"        <DaysInterval>1</DaysInterval>\n"
        L"      </ScheduleByDay>\n"
        L"    </CalendarTrigger>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2017-01-01T06:10:00</StartBoundary>\n"
        L"      <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"      <RandomDelay>PT4H</RandomDelay>\n"
        L"      <ScheduleByDay>\n"
        L"        <DaysInterval>1</DaysInterval>\n"
        L"      </ScheduleByDay>\n"
        L"    </CalendarTrigger>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2017-01-01T10:10:00</StartBoundary>\n"
        L"      <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"      <RandomDelay>PT4H</RandomDelay>\n"
        L"      <ScheduleByDay>\n"
        L"        <DaysInterval>1</DaysInterval>\n"
        L"      </ScheduleByDay>\n"
        L"    </CalendarTrigger>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2017-01-01T14:10:00</StartBoundary>\n"
        L"      <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"      <RandomDelay>PT4H</RandomDelay>\n"
        L"      <ScheduleByDay>\n"
        L"        <DaysInterval>1</DaysInterval>\n"
        L"      </ScheduleByDay>\n"
        L"    </CalendarTrigger>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2017-01-01T18:10:00</StartBoundary>\n"
        L"      <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"      <RandomDelay>PT4H</RandomDelay>\n"
        L"      <ScheduleByDay>\n"
        L"        <DaysInterval>1</DaysInterval>\n"
        L"      </ScheduleByDay>\n"
        L"    </CalendarTrigger>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2017-01-01T22:10:00</StartBoundary>\n"
        L"      <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"      <RandomDelay>PT4H</RandomDelay>\n"
        L"      <ScheduleByDay>\n"
        L"        <DaysInterval>1</DaysInterval>\n"
        L"      </ScheduleByDay>\n"
        L"    </CalendarTrigger>\n"
        L"  </Triggers>\n"
        L"  <Actions Context=\"Author\">\n"
        L"    <Exec>\n"
        L"      <Command>C:\\Program Files\\Microsoft Office\\root\\Office16\\sdxhelper.exe</Command>\n"
        L"    </Exec>\n"
        L"  </Actions>\n"
        L"</Task>"
    },
    {"Office_Feature_Updates_C2R_Client",
        L"<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n"
        L"<Task version=\"1.3\" xmlns=\"http://schemas.microsoft.com/windows/2004/02/mit/task\">\n"
        L"  <RegistrationInfo>\n"
        L"    <Version>16.0.0</Version>\n"
        L"    <Date>2017-01-01T00:00:00</Date>\n"
        L"    <Author>Microsoft Office</Author>\n"
        L"    <Description>This task ensures that your Microsoft Office installation can check for feature updates.</Description>\n"
        L"    <URI>\\Microsoft\\Office\\Office Feature Updates C2R Client</URI>\n"
        L"  </RegistrationInfo>\n"
        L"  <Principals>\n"
        L"    <Principal id=\"Author\">\n"
        L"      <GroupId>S-1-5-32-545</GroupId>\n"
        L"    </Principal>\n"
        L"  </Principals>\n"
        L"  <Settings>\n"
        L"    <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>\n"
        L"    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>\n"
        L"    <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n"
        L"    <RunOnlyIfNetworkAvailable>true</RunOnlyIfNetworkAvailable>\n"
        L"    <IdleSettings>\n"
        L"      <StopOnIdleEnd>false</StopOnIdleEnd>\n"
        L"      <RestartOnIdle>false</RestartOnIdle>\n"
        L"    </IdleSettings>\n"
        L"    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\n"
        L"  </Settings>\n"
        L"  <Triggers>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2017-01-01T02:10:00</StartBoundary>\n"
        L"      <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"      <RandomDelay>PT4H</RandomDelay>\n"
        L"      <ScheduleByDay>\n"
        L"        <DaysInterval>1</DaysInterval>\n"
        L"      </ScheduleByDay>\n"
        L"    </CalendarTrigger>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2017-01-01T06:10:00</StartBoundary>\n"
        L"      <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"      <RandomDelay>PT4H</RandomDelay>\n"
        L"      <ScheduleByDay>\n"
        L"        <DaysInterval>1</DaysInterval>\n"
        L"      </ScheduleByDay>\n"
        L"    </CalendarTrigger>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2017-01-01T10:10:00</StartBoundary>\n"
        L"      <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"      <RandomDelay>PT4H</RandomDelay>\n"
        L"      <ScheduleByDay>\n"
        L"        <DaysInterval>1</DaysInterval>\n"
        L"      </ScheduleByDay>\n"
        L"    </CalendarTrigger>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2017-01-01T14:10:00</StartBoundary>\n"
        L"      <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"      <RandomDelay>PT4H</RandomDelay>\n"
        L"      <ScheduleByDay>\n"
        L"        <DaysInterval>1</DaysInterval>\n"
        L"      </ScheduleByDay>\n"
        L"    </CalendarTrigger>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2017-01-01T18:10:00</StartBoundary>\n"
        L"      <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"      <RandomDelay>PT4H</RandomDelay>\n"
        L"      <ScheduleByDay>\n"
        L"        <DaysInterval>1</DaysInterval>\n"
        L"      </ScheduleByDay>\n"
        L"    </CalendarTrigger>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2017-01-01T22:10:00</StartBoundary>\n"
        L"      <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"      <RandomDelay>PT4H</RandomDelay>\n"
        L"      <ScheduleByDay>\n"
        L"        <DaysInterval>1</DaysInterval>\n"
        L"      </ScheduleByDay>\n"
        L"    </CalendarTrigger>\n"
        L"  </Triggers>\n"
        L"  <Actions Context=\"Author\">\n"
        L"    <Exec>\n"
        L"      <Command>%CommonProgramFiles%\\Microsoft Shared\\ClickToRun\\OfficeC2RClient.exe</Command>\n"
        L"      <Arguments>/installupdatesdx</Arguments>\n"
        L"    </Exec>\n"
        L"  </Actions>\n"
        L"</Task>"
    },
    {"Office_Feature_Updates_C2R_Client_Logon",
        L"<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n"
        L"<Task version=\"1.3\" xmlns=\"http://schemas.microsoft.com/windows/2004/02/mit/task\">\n"
        L"  <RegistrationInfo>\n"
        L"    <Version>16.0.0</Version>\n"
        L"    <Date>2017-01-01T00:00:00</Date>\n"
        L"    <Author>Microsoft Office</Author>\n"
        L"    <Description>This task ensures that your Microsoft Office installation can check for feature updates.</Description>\n"
        L"    <URI>\\Microsoft\\Office\\Office Feature Updates C2R Client Logon</URI>\n"
        L"  </RegistrationInfo>\n"
        L"  <Principals>\n"
        L"    <Principal id=\"Author\">\n"
        L"      <GroupId>S-1-5-32-545</GroupId>\n"
        L"    </Principal>\n"
        L"  </Principals>\n"
        L"  <Settings>\n"
        L"    <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>\n"
        L"    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>\n"
        L"    <ExecutionTimeLimit>PT30M</ExecutionTimeLimit>\n"
        L"    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n"
        L"    <RunOnlyIfNetworkAvailable>true</RunOnlyIfNetworkAvailable>\n"
        L"    <IdleSettings>\n"
        L"      <StopOnIdleEnd>false</StopOnIdleEnd>\n"
        L"      <RestartOnIdle>false</RestartOnIdle>\n"
        L"    </IdleSettings>\n"
        L"    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\n"
        L"  </Settings>\n"
        L"  <Triggers>\n"
        L"    <LogonTrigger>\n"
        L"      <ExecutionTimeLimit>PT30M</ExecutionTimeLimit>\n"
        L"      <Delay>PT15M</Delay>\n"
        L"    </LogonTrigger>\n"
        L"    <SessionStateChangeTrigger>\n"
        L"      <ExecutionTimeLimit>PT30M</ExecutionTimeLimit>\n"
        L"      <Delay>PT15M</Delay>\n"
        L"      <StateChange>SessionUnlock</StateChange>\n"
        L"    </SessionStateChangeTrigger>\n"
        L"  </Triggers>\n"
        L"  <Actions Context=\"Author\">\n"
        L"    <Exec>\n"
        L"      <Command>%CommonProgramFiles%\\Microsoft Shared\\ClickToRun\\OfficeC2RClient.exe</Command>\n"
        L"      <Arguments>/installupdatesdx</Arguments>\n"
        L"    </Exec>\n"
        L"  </Actions>\n"
        L"</Task>"
    },
    {"Office_Feature_Updates_Logon",
        L"<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n"
        L"<Task version=\"1.3\" xmlns=\"http://schemas.microsoft.com/windows/2004/02/mit/task\">\n"
        L"  <RegistrationInfo>\n"
        L"    <Version>16.0.0</Version>\n"
        L"    <Date>2017-01-01T00:00:00</Date>\n"
        L"    <Author>Microsoft Office</Author>\n"
        L"    <Description>This task ensures that your Microsoft Office installation can check for feature updates.</Description>\n"
        L"    <URI>\\Microsoft\\Office\\Office Feature Updates Logon</URI>\n"
        L"  </RegistrationInfo>\n"
        L"  <Principals>\n"
        L"    <Principal id=\"Author\">\n"
        L"      <GroupId>S-1-5-32-545</GroupId>\n"
        L"    </Principal>\n"
        L"  </Principals>\n"
        L"  <Settings>\n"
        L"    <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>\n"
        L"    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>\n"
        L"    <ExecutionTimeLimit>PT30M</ExecutionTimeLimit>\n"
        L"    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n"
        L"    <RunOnlyIfNetworkAvailable>true</RunOnlyIfNetworkAvailable>\n"
        L"    <IdleSettings>\n"
        L"      <StopOnIdleEnd>false</StopOnIdleEnd>\n"
        L"      <RestartOnIdle>false</RestartOnIdle>\n"
        L"    </IdleSettings>\n"
        L"    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>\n"
        L"  </Settings>\n"
        L"  <Triggers>\n"
        L"    <LogonTrigger>\n"
        L"      <ExecutionTimeLimit>PT30M</ExecutionTimeLimit>\n"
        L"      <Delay>PT15M</Delay>\n"
        L"    </LogonTrigger>\n"
        L"    <SessionStateChangeTrigger>\n"
        L"      <ExecutionTimeLimit>PT30M</ExecutionTimeLimit>\n"
        L"      <Delay>PT15M</Delay>\n"
        L"      <StateChange>SessionUnlock</StateChange>\n"
        L"    </SessionStateChangeTrigger>\n"
        L"  </Triggers>\n"
        L"  <Actions Context=\"Author\">\n"
        L"    <Exec>\n"
        L"      <Command>C:\\Program Files\\Microsoft Office\\root\\Office16\\sdxhelper.exe</Command>\n"
        L"      <Arguments>/onlogon</Arguments>\n"
        L"    </Exec>\n"
        L"  </Actions>\n"
        L"</Task>"
    },
    {"Office_Performance_Monitor",
        L"<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n"
        L"<Task version=\"1.2\" xmlns=\"http://schemas.microsoft.com/windows/2004/02/mit/task\">\n"
        L"  <RegistrationInfo>\n"
        L"    <Description>This task ensures that your Microsoft Office installation can be monitored for performance issues.</Description>\n"
        L"    <URI>\\Microsoft\\Office\\Office Performance Monitor</URI>\n"
        L"  </RegistrationInfo>\n"
        L"  <Principals>\n"
        L"    <Principal id=\"Author\">\n"
        L"      <UserId>S-1-5-18</UserId>\n"
        L"      <RunLevel>HighestAvailable</RunLevel>\n"
        L"    </Principal>\n"
        L"  </Principals>\n"
        L"  <Settings>\n"
        L"    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n"
        L"    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n"
        L"    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\n"
        L"    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n"
        L"    <StartWhenAvailable>true</StartWhenAvailable>\n"
        L"    <IdleSettings>\n"
        L"      <StopOnIdleEnd>false</StopOnIdleEnd>\n"
        L"      <RestartOnIdle>false</RestartOnIdle>\n"
        L"    </IdleSettings>\n"
        L"  </Settings>\n"
        L"  <Triggers>\n"
        L"    <EventTrigger>\n"
        L"      <Subscription>&lt;QueryList&gt;&lt;Query Id=\"0\" Path=\"Application\"&gt;&lt;Select Path=\"Application\"&gt;*[System[Provider[@Name='Microsoft Office 16'] and EventID=2050]]&lt;/Select&gt;&lt;/Query&gt;&lt;/QueryList&gt;</Subscription>\n"
        L"    </EventTrigger>\n"
        L"  </Triggers>\n"
        L"  <Actions Context=\"Author\">\n"
        L"    <Exec>\n"
        L"      <Command>C:\\Program Files\\Microsoft Office\\root\\VFS\\ProgramFilesCommonX64\\Microsoft Shared\\Office16\\operfmon.exe</Command>\n"
        L"    </Exec>\n"
        L"  </Actions>\n"
        L"</Task>"
    },
    {"Office_Startup_Maintenance",
        L"<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n"
        L"<Task version=\"1.2\" xmlns=\"http://schemas.microsoft.com/windows/2004/02/mit/task\">\n"
        L"  <RegistrationInfo>\n"
        L"    <Description>This task updates the availability states of Office features</Description>\n"
        L"    <URI>\\Microsoft\\Office\\Office Startup Maintenance</URI>\n"
        L"  </RegistrationInfo>\n"
        L"  <Principals>\n"
        L"    <Principal id=\"Author\">\n"
        L"      <GroupId>S-1-5-32-545</GroupId>\n"
        L"    </Principal>\n"
        L"  </Principals>\n"
        L"  <Settings>\n"
        L"    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n"
        L"    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n"
        L"    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\n"
        L"    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n"
        L"    <StartWhenAvailable>true</StartWhenAvailable>\n"
        L"    <IdleSettings>\n"
        L"      <StopOnIdleEnd>false</StopOnIdleEnd>\n"
        L"      <RestartOnIdle>false</RestartOnIdle>\n"
        L"    </IdleSettings>\n"
        L"  </Settings>\n"
        L"  <Triggers>\n"
        L"    <LogonTrigger>\n"
        L"      <ExecutionTimeLimit>PT3M</ExecutionTimeLimit>\n"
        L"      <Delay>PT15M</Delay>\n"
        L"    </LogonTrigger>\n"
        L"    <CalendarTrigger>\n"
        L"      <StartBoundary>2025-10-23T08:00:00</StartBoundary>\n"
        L"      <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>\n"
        L"      <RandomDelay>PT1H</RandomDelay>\n"
        L"      <ScheduleByDay>\n"
        L"        <DaysInterval>1</DaysInterval>\n"
        L"      </ScheduleByDay>\n"
        L"    </CalendarTrigger>\n"
        L"  </Triggers>\n"
        L"  <Actions Context=\"Author\">\n"
        L"    <Exec>\n"
        L"      <Command>C:\\Program Files\\Microsoft Office\\root\\VFS\\ProgramFilesCommonX64\\Microsoft Shared\\Office16\\ActionsServer\\ActionsServer.exe</Command>\n"
        L"      <Arguments>wacheck</Arguments>\n"
        L"    </Exec>\n"
        L"  </Actions>\n"
        L"</Task>"
    },
};
