#!/usr/bin/python3
# make-samples.py: the WebP files wicwebpprobe decodes -- one picture, deterministic, in each kind of WebP
from PIL import Image, ImageDraw
import os
here = os.path.dirname(os.path.abspath(__file__))

def picture(w, h, alpha=False, shift=0):
    im = Image.new('RGBA', (w, h))
    px = im.load()
    for y in range(h):
        for x in range(w):
            px[x, y] = ((x * 255 // (w - 1) + shift) % 256, y * 255 // (h - 1), (x + y + shift) % 256,
                        (255 - x * 2) % 256 if alpha else 255)
    d = ImageDraw.Draw(im)
    d.rectangle((10 + shift % 20, 10, 40 + shift % 20, 30), fill=(255, 255, 0, 200 if alpha else 255))
    d.ellipse((50, 20, 90, 60), outline=(0, 0, 255, 255), width=3)
    return im if alpha else im.convert('RGB')

picture(96, 64).save(os.path.join(here, 'lossy.webp'), 'WEBP', quality=80, method=4)
picture(96, 64).save(os.path.join(here, 'lossless.webp'), 'WEBP', lossless=True, method=4)
picture(96, 64, True).save(os.path.join(here, 'lossy-alpha.webp'), 'WEBP', quality=80, method=4, alpha_quality=100)
picture(96, 64, True).save(os.path.join(here, 'lossless-alpha.webp'), 'WEBP', lossless=True, method=4)
picture(33, 17).save(os.path.join(here, 'odd-size.webp'), 'WEBP', quality=90, method=4)
frames = [picture(64, 48, i == 1, i * 17) for i in range(3)]
frames[0].save(os.path.join(here, 'animated.webp'), 'WEBP', save_all=True, append_images=frames[1:],
               duration=[100, 200, 300], loop=0, lossless=True)
frames[0].save(os.path.join(here, 'animated-lossy.webp'), 'WEBP', save_all=True, append_images=frames[1:],
               duration=80, loop=3, quality=70, background=(10, 20, 30, 40))

# samples.h: the files as arrays for the probe, with four broken ones made from them
names = ['lossy', 'lossless', 'lossy-alpha', 'lossless-alpha', 'odd-size', 'animated', 'animated-lossy']
data = {n: open(os.path.join(here, n + '.webp'), 'rb').read() for n in names}
odd, anim = data['odd-size'], data['animated']
broken = {'truncated': odd[:40], 'damaged': odd[:60] + b'\x55' * (len(odd) - 60),
          'truncated-animation': anim[:900], 'header-only': odd[:12]}
out = ['/* generated by samples/make-samples.py and the lines at the end of it */', '']
def array(n, d, spaced):
    out.append('static const unsigned char sample_%s[] = {' % n.replace('-', '_'))
    for i in range(0, len(d), 16):
        out.append('    ' + (', ' if spaced else ',').join('0x%02x' % b for b in d[i:i + 16]) + ',')
    out.append('};')
for n in names: array(n, data[n], True)
for n, d in broken.items(): array(n, d, True)
out.append('static const struct { const char *name; const unsigned char *data; unsigned int size; } samples[] =')
out.append('{')
for n in names:
    out.append('    { "%s.webp", sample_%s, sizeof(sample_%s) },' % (n, n.replace('-', '_'), n.replace('-', '_')))
out.append('    /* cut short, damaged past the header, an animation cut short, and nothing but the header */')
for n in broken:
    out.append('    { "%s.webp", sample_%s, sizeof(sample_%s) },' % (n, n.replace('-', '_'), n.replace('-', '_')))
out.append('};')
open(os.path.join(here, '..', 'samples.h'), 'w').write('\n'.join(out) + '\n')
